import type { Metadata } from 'next';
import '../public/styles/global.css';
import Nav from '@/components/common/nav';
import Footer from '@/components/common/footer';
import ReactQueryClientProvider from '@/config/ReactQueryClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <head></head>

        <body>
          <Nav />

          <div className="max-w-7xl mx-auto px-10 py-32">
            <div className="">{children}</div>
          </div>

          <Footer />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
